//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.11 at 11:14:09 AM CEST 
//


package it.poste.postspy.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="services_base_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="local_ip_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="local_mac_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "servicesBasePath",
    "localIpAddress",
    "localMacAddress"
})
@XmlRootElement(name = "remote_settings")
public class RemoteSettings {

    @XmlElement(name = "services_base_path", required = true)
    protected String servicesBasePath;
    @XmlElement(name = "local_ip_address", required = true)
    protected String localIpAddress;
    @XmlElement(name = "local_mac_address", required = true)
    protected String localMacAddress;

    /**
     * Gets the value of the servicesBasePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicesBasePath() {
        return servicesBasePath;
    }

    /**
     * Sets the value of the servicesBasePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicesBasePath(String value) {
        this.servicesBasePath = value;
    }

    /**
     * Gets the value of the localIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalIpAddress() {
        return localIpAddress;
    }

    /**
     * Sets the value of the localIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalIpAddress(String value) {
        this.localIpAddress = value;
    }

    /**
     * Gets the value of the localMacAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalMacAddress() {
        return localMacAddress;
    }

    /**
     * Sets the value of the localMacAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalMacAddress(String value) {
        this.localMacAddress = value;
    }

}
